### ISSUE TITLE
require': cannot load such file -- haml (LoadError)

### ISSUE THREAD

**Issue by jitendravyas** [dandenney/emayll#2]
I'm getting this error when I run jekyll serve

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- haml (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by dandenney** [comment]
Yikes, has it been working for a while or are you just jumping back into it? I'm still able to run it but that seems like the Haml plugin isn't working properly.

**Comment by jitendravyas** [comment]
oh I have not installed the HAML plugin. Can you tell me how to install it?
